require('./config/db.config')
const userRoute = require('./routes/userRoute')
const productTypeRoute = require('./routes/productTypeRoute')
const ProductsRoute = require('./routes/productRoute')
const ldcRoute = require('./routes/ldcRoute')
const express = require('express')
const app =express()
app.use(express.json())
app.use(userRoute)
app.use(productTypeRoute)
app.use(ProductsRoute)
app.use(ldcRoute)
app.listen(3000,()=>{
    console.log('connected')
})

// const User = require('./Models/userModel')
// User.insertMany({name:"rajesh",email:"123gmail.com"})